name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend   # backend なら ./backend
      - name: Run tests
        run: npm test -- --coverage
        working-directory: ./frontend
      - name: Build
        run: npm run build
        working-directory: ./frontend
